import { Component } from '@angular/core';
import { IonicModule } from '@ionic/angular';
import { HeaderComponent } from '../../../../shared/components/header/header.component';
import { TabelaComponent } from '../../components/tabela/tabela.component';
import { CardValorComponent } from '../../../financeiro/components/card-valor/card-valor.component';
import { Aluno } from '../../../../../types/Aluno';

@Component({
  selector: 'app-alunos',
  imports: [IonicModule, HeaderComponent, TabelaComponent, CardValorComponent],
  templateUrl: './alunos.component.html',
  styleUrl: './alunos.component.css',
})
export class AlunosComponent {
  alunos: Aluno[] = [
    {
      id: 1,
      nome: 'Ana Beatriz Souza',
      dataNascimento: '2012-03-12',
      rg: '12.345.678-9',
      tipoSanguineo: 'A+',
      valor: 200,
      responsaveis: [1],
      endereco: {
        id: 1,
        cep: '06700-000',
        rua: 'Rua das Acácias',
        bairro: 'Jardim Central',
        cidade: 'Cotia',
        estado: 'SP',
        latitude: -23.6039,
        longitude: -46.9189,
      },
      rota: {
        id: 1,
        nome: 'Rota Centro',
        turno: 'Manhã',
        ativa: 1,
        escola: {
          id: 1,
          nome: 'E.E. Jornalista Corte Real',
          tipo: 2,
          telefone: '(11) 9 6617-7782',
          status: 1,
          endereco: {
            id: 1,
            cep: '06700-000',
            rua: 'Rua das Acácias',
            bairro: 'Jardim Central',
            cidade: 'Cotia',
            estado: 'SP',
          },
        },
        van: {
          id: 1,
          numero: 12,
          placa: 'ABC-1D23',
          renavam: 3242432,
          lugares: 16,
          marca: 1,
          modelo: 'Sprinter',
          status: 1,
        },
        motorista: {
          id: 1,
          nome: 'Roberto Carlos',
          dataNascimento: '1994-11-04',
          telefone: '(11) 9 6610-1101',
          cnh: '4322525253223',
          cpf: '4322525253223',
          dataValidadeCnh: '2026-11-04',
        },
        horario_inicio_ida: '06:00',
        horario_fim_ida: '07:00',
        horario_inicio_volta: '12:00',
        horario_fim_volta: '13:00',
      },
      status: 2,
    },
    {
      id: 2,
      nome: 'Gabriel Eduardo Rocha',
      dataNascimento: '2011-08-15',
      rg: '45.678.123-9',
      tipoSanguineo: 'O+',
      valor: 200,
      responsaveis: [2],
      endereco: {
        id: 2,
        cep: '06701-000',
        rua: 'Rua das Flores',
        bairro: 'Jardim das Rosas',
        cidade: 'Cotia',
        estado: 'SP',
        latitude: -23.6045,
        longitude: -46.919,
      },
      rota: {
        id: 2,
        nome: 'Rota Leste',
        turno: 'Tarde',
        ativa: 1,
        escola: {
          id: 2,
          nome: 'E.M. Paulo Freire',
          tipo: 1,
          telefone: '(11) 9 6611-2233',
          status: 1,
          endereco: {
            id: 2,
            cep: '06701-000',
            rua: 'Rua das Flores',
            bairro: 'Jardim das Rosas',
            cidade: 'Cotia',
            estado: 'SP',
          },
        },
        van: {
          id: 2,
          numero: 5,
          placa: 'XYZ-2F45',
          renavam: 3242432,
          lugares: 12,
          marca: 2,
          modelo: 'Fiat Ducato',
          status: 1,
        },
        motorista: {
          id: 2,
          nome: 'Marcos Vinicius',
          dataNascimento: '1988-07-20',
          telefone: '(11) 9 6622-3344',
          cnh: '1234567890123',
          cpf: '1234567890123',
          dataValidadeCnh: '2027-07-20',
        },
        horario_inicio_ida: '13:00',
        horario_fim_ida: '14:00',
        horario_inicio_volta: '17:00',
        horario_fim_volta: '18:00',
      },
      status: 1,
    },
    {
      id: 3,
      nome: 'Letícia Martins',
      dataNascimento: '2013-02-28',
      rg: '33.444.555-6',
      tipoSanguineo: 'B-',
      valor: 200,
      responsaveis: [3],
      endereco: {
        id: 3,
        cep: '06702-000',
        rua: 'Rua das Palmeiras',
        bairro: 'Jardim Primavera',
        cidade: 'Cotia',
        estado: 'SP',
        latitude: -23.605,
        longitude: -46.92,
      },
      rota: {
        id: 1, // mesma rota de Ana Beatriz
        nome: 'Rota Centro',
        turno: 'Manhã',
        ativa: 1,
        escola: {
          id: 1,
          nome: 'E.E. Jornalista Corte Real',
          tipo: 2,
          telefone: '(11) 9 6617-7782',
          status: 1,
          endereco: {
            id: 1,
            cep: '06700-000',
            rua: 'Rua das Acácias',
            bairro: 'Jardim Central',
            cidade: 'Cotia',
            estado: 'SP',
          },
        },
        van: {
          id: 1,
          numero: 12,
          placa: 'ABC-1D23',
          renavam: 3242432,
          lugares: 16,
          marca: 1,
          modelo: 'Sprinter',
          status: 1,
        },
        motorista: {
          id: 1,
          nome: 'Roberto Carlos',
          dataNascimento: '1994-11-04',
          telefone: '(11) 9 6610-1101',
          cnh: '4322525253223',
          cpf: '4322525253223',
          dataValidadeCnh: '2026-11-04',
        },
        horario_inicio_ida: '06:00',
        horario_fim_ida: '07:00',
        horario_inicio_volta: '12:00',
        horario_fim_volta: '13:00',
      },
      status: 2,
    },
    {
      id: 4,
      nome: 'Lucas Almeida',
      dataNascimento: '2012-09-10',
      rg: '22.333.444-5',
      tipoSanguineo: 'AB+',
      valor: 200,
      responsaveis: [4],
      endereco: {
        id: 4,
        cep: '06703-000',
        rua: 'Rua do Sol',
        bairro: 'Jardim do Sol',
        cidade: 'Cotia',
        estado: 'SP',
        latitude: -23.606,
        longitude: -46.921,
      },
      rota: {
        id: 2, // mesma rota de Gabriel
        nome: 'Rota Leste',
        turno: 'Tarde',
        ativa: 1,
        escola: {
          id: 2,
          nome: 'E.M. Paulo Freire',
          tipo: 1,
          telefone: '(11) 9 6611-2233',
          status: 1,
          endereco: {
            id: 2,
            cep: '06701-000',
            rua: 'Rua das Flores',
            bairro: 'Jardim das Rosas',
            cidade: 'Cotia',
            estado: 'SP',
          },
        },
        van: {
          id: 2,
          numero: 5,
          placa: 'XYZ-2F45',
          lugares: 12,
          renavam: 3242432,
          marca: 2,
          modelo: 'Fiat Ducato',
          status: 1,
        },
        motorista: {
          id: 2,
          nome: 'Marcos Vinicius',
          dataNascimento: '1988-07-20',
          telefone: '(11) 9 6622-3344',
          cnh: '1234567890123',
          cpf: '1234567890123',
          dataValidadeCnh: '2027-07-20',
        },
        horario_inicio_ida: '13:00',
        horario_fim_ida: '14:00',
        horario_inicio_volta: '17:00',
        horario_fim_volta: '18:00',
      },
      status: 1,
    },
  ];
}
